### ISSUE TITLE
Japanese quotation mark left in

### ISSUE THREAD

**Issue by jswhitney7** [Ich73/DQM2-FanTranslation#11]
Not an issue, per say, but these smaller things can add up to justify a new version of the patch. Right at the start, where you meet the large monster in the cave after climbing the ladder, there’s a Japanese quotation mark left in the sentence. I’ve attached a photo. 

Seriously cannot thank y’all enough, am truly grateful we can finally play this title in English. Thanks! 
![AEAC5D1E-D69B-468F-BF46-0E922A7515C2](https://user-images.githubusercontent.com/32251358/113496708-f8480300-94c1-11eb-9785-06b5a5f5a0fa.jpeg)

**Comment by Ich73** [comment]
If you're using a LayeredFS patch, you can now [update your workspace](https://github.com/Ich73/DQM2-FanTranslation/wiki/Installing-LayeredFS#update-workspace) using the UW script.
