### ISSUE TITLE
text errors (through water world)

### ISSUE THREAD

**Issue by dackst** [Ich73/DQM2-FanTranslation#13]
I've been collecting a bunch of stuff as I've played through 1.0. I played through the end of the desert world with Tara, but only the opening scenes with Cobi. Sorry if some of these have been fixed already with the post-1.0 commits. I tried to make sure nothing overlaps with any other currently open issues.

* ["What what"](https://user-images.githubusercontent.com/35816592/113505780-03755000-950f-11eb-9820-65d0f5c65f86.png) should be "what was"
  * Tobi equivalent: "[What's that](https://user-images.githubusercontent.com/35816592/113515788-94b2e980-9544-11eb-8587-172e522e4f50.png)" should also be "What was that". Also "All I saw was" or "All I could see was" By the time he says this, the monster is no longer visible.
* [It's gonna eat](https://user-images.githubusercontent.com/35816592/113515931-68e43380-9545-11eb-8dba-b71d1f4b50a5.png) ***us***?

* unexpected line breaks? [1](https://user-images.githubusercontent.com/35816592/113505816-31f32b00-950f-11eb-88aa-3cca3b6b3fd4.png), [2](https://user-images.githubusercontent.com/35816592/113507155-c6ad5700-9516-11eb-83bf-99ce851f5fab.png)
* [line break comes too late](https://user-images.githubusercontent.com/35816592/113507905-2148b200-951b-11eb-94bb-d6857d2c328c.png)
* not enough space [here](https://user-images.githubusercontent.com/35816592/113506060-7af7af00-9510-11eb-853f-21d60dc1ee67.png)
* too much space [here](https://user-images.githubusercontent.com/35816592/113506075-8f3bac00-9510-11eb-8b70-ccc7b6940868.png)
* [how it current looks](https://user-images.githubusercontent.com/35816592/113506100-bbefc380-9510-11eb-9474-4fd674b8e377.png) -> how it ***currently*** looks
* [worlds within worlds](https://user-images.githubusercontent.com/35816592/113506132-fd806e80-9510-11eb-88e0-5e928b20439c.png): I doubt this is supposed to mean that other worlds are somehow contained within Great Log's world, and think that "within our" is mistakenly repeated twice.
* [whither](https://user-images.githubusercontent.com/35816592/113506190-518b5300-9511-11eb-8698-6018e0ea4108.png): Whither is a word that exists, but the correct word here is "wither"
* [Great Log wither](https://user-images.githubusercontent.com/35816592/113506216-7a134d00-9511-11eb-889d-014b65b11556.png) -> Great log ***will*** wither
* [Scout help](https://user-images.githubusercontent.com/35816592/113506246-a5963780-9511-11eb-98dd-2ce13bc71df1.png):
  * monsters' -> monsters
  * lands -> land's
  * "known throughout the world" implies the text applies to the world of Great Log/Tree, while "worlds' strongest" implies it applies to all the worlds. I feel like it should be either one or the other. Might also apply to the earlier "monsters['] of this world"
* [whistling](https://user-images.githubusercontent.com/35816592/113506538-77195c00-9513-11eb-9cd2-4c6aaecaedb2.png) -> Whistle, to be consistent with how the other actions are written
* [iou](https://user-images.githubusercontent.com/35816592/113508591-ec3e5e80-951e-11eb-9559-9b6f48eeeb16.png) -> you
* [we're not in Great Tree anymore](https://user-images.githubusercontent.com/35816592/113508602-fceed480-951e-11eb-81b9-48fd1493ce60.png)

* [kameha](https://user-images.githubusercontent.com/35816592/113506325-310fc880-9512-11eb-886b-3fcfb0c0a5bb.png): he going to -> he ***is*** going to, near king -> ***next*** king
* [words](https://user-images.githubusercontent.com/35816592/113506437-e80c4400-9512-11eb-9f2b-d1569e76dd30.png) -> worlds
* [I'd be happy when he'll return home](https://user-images.githubusercontent.com/35816592/113506577-a7f99100-9513-11eb-936c-4fa7124eccfc.png) -> ***I'll*** be happy when ***he returns*** home? I'd be happy ***if he returns*** home?
* [guard on Kameha](https://user-images.githubusercontent.com/35816592/113506880-53efac00-9515-11eb-8079-82aad30afb01.png): this doesn't make much sense as is. I mean, of course the guard is relieved he doesn't have to deal with him, but the fact that Prince Kameha hasn't shown up where he usually would should make the guard more worried about the idea that Kameha might be missing.
* [an audience with his this country's ruler](https://user-images.githubusercontent.com/35816592/113506999-e3955a80-9515-11eb-9310-af4583b18a81.png): don't remember the exact line before this, but the "his" could probably be removed. Depending on what came before, maybe it could be "an audience with ***him,*** this country's ruler", or something
* [The Bandit's leader](https://user-images.githubusercontent.com/35816592/113507119-9796e580-9516-11eb-9266-126d5f389fe3.png) -> The bandit leader, The bandits' leader (There's more than one bandit)
* [Brethern](https://user-images.githubusercontent.com/35816592/113507193-070cd500-9517-11eb-82ce-aa9ae5c1a85c.png) is spelled *brethren*, and probably should be possessive (brethren's). But this sentence has some weird sounding nested possessive stuff, and I'd rather not try to figure out what is "correct". It would be ideally restructured altogether (Maybe "Come to most any inn you come across during your travels to seek a blessing from me and my brethren.")
* [are resting at the Inn](https://user-images.githubusercontent.com/35816592/113507447-7df69d80-9518-11eb-9fad-29bcb9bf894b.png): There's only one dude at the inn. This implies all, or at least a group of performers are in the inn. 
* [Better hurry after him then...](https://user-images.githubusercontent.com/35816592/113507524-168d1d80-9519-11eb-9887-3b1fcfd933ef.png): this line makes no sense in context; we're not chasing after anyone. What I *think* he meant to say is that he wants to finish exploring before Papa gets back.
* [folks](https://user-images.githubusercontent.com/35816592/113507561-5e13a980-9519-11eb-80f1-2ad52a41d814.png) -> folks' 
* [Slush](https://user-images.githubusercontent.com/35816592/113507592-7b487800-9519-11eb-9b73-000b375fe158.png) joins your party, but he's named [Slash](https://user-images.githubusercontent.com/35816592/113507604-8bf8ee00-9519-11eb-9612-642423d2ee23.png) while in it.
* Cobi: [what awaits you there](https://user-images.githubusercontent.com/35816592/113507615-a16e1800-9519-11eb-9716-3dab9973a5fc.png) I thought he wanted to explore together?
* Beasts: [1](https://user-images.githubusercontent.com/35816592/113507654-dd08e200-9519-11eb-99a5-e4ae4e449cb6.png), [2](https://user-images.githubusercontent.com/35816592/113507665-f01bb200-9519-11eb-90d0-2c6bf15028a5.png)], [3](https://user-images.githubusercontent.com/35816592/114855957-7f478600-9db4-11eb-94cd-b4e70f69dff1.png): there are no beast family monsters anywhere. maybe something like beastly? for 2+3, "that monster over there" is a devipine, which is in the devil family. there are also florajays further down the map, which are nature.

* [don't forget that Drake slime](https://user-images.githubusercontent.com/35816592/113515680-f9217900-9543-11eb-831d-d0b037b2179e.png): he doesn't seem to have a name like Slush. Can't remember how other generic monster names are used, but either "don't forget that the Drake Slime" or "don't forget that the drake slime"

* [townsfolk](https://user-images.githubusercontent.com/35816592/113507793-9b2c6b80-951a-11eb-9cb8-886656c3b772.png) is typically one word
* The [second desert town](https://user-images.githubusercontent.com/35816592/113507877-02e2b680-951b-11eb-839f-f30a7592ae1d.png) is referred to as both "Asiya" and "Asyia" is multiple areas.
* [all of the sudden](https://user-images.githubusercontent.com/35816592/113507915-3d4c5380-951b-11eb-9d88-d6995be35dec.png): from what I could find, while "all of the sudden" has found some recent online usage, the typical phrase is "all of a sudden"
* [Antidotal herb](https://user-images.githubusercontent.com/35816592/113508495-4e4a9400-951e-11eb-8896-5abaadcde430.png) would be better as "Cures a single ally of the effects of poison or severe poison" to be consistent with the [other status healing items](https://user-images.githubusercontent.com/35816592/113508548-9a95d400-951e-11eb-9340-5337c96565a2.png)
 in the item shop

* [towns underground aquaduct](https://user-images.githubusercontent.com/35816592/113508666-4808e780-951f-11eb-9bff-ba7272f80d3d.png) -> town's underground aqueduct. Besides this one, there also many more instances of "aqueduct" being misspelled as "aquaduct". "Aquaeduct" seems to also be a viable alternative, but the "aqueducts" should probably change too if that is chosen

* [discretely](https://user-images.githubusercontent.com/35816592/113507978-8a302a00-951b-11eb-8779-4f480c089122.png) -> discreetly
* [What in the... was that voice...?](https://user-images.githubusercontent.com/35816592/113508072-f27f0b80-951b-11eb-9df8-795cb2d2c498.png) -> "What in the... ***What*** was that voice...?", "What in the ***world*** was that voice...?"
* [I can see you're concern for my safety](https://user-images.githubusercontent.com/35816592/113508115-2a864e80-951c-11eb-83ba-b029db3870d8.png) -> "I can see you're concern***ed*** for my safety", or possibly,  "I can see ***your*** concern for my safety"
* [it can't hurt to have by my side](https://user-images.githubusercontent.com/35816592/113508164-7c2ed900-951c-11eb-9aa7-a9ef07539675.png) -> it can't hurt to have ***you*** by my side
* [Passageway](https://user-images.githubusercontent.com/35816592/113508191-9e285b80-951c-11eb-9bc0-50749523c187.png) is typically one word
* [existance](https://user-images.githubusercontent.com/35816592/113508216-b8623980-951c-11eb-8db9-397fc2dc72be.png) -> existence
* [line](https://user-images.githubusercontent.com/35816592/113508230-cd3ecd00-951c-11eb-87c6-488ef58b7ed2.png) -> "where did the "Ringmaster" ***go***...? ***It's*** almost like he vanished
* [have you been gaining skill points](https://user-images.githubusercontent.com/35816592/113508265-07a86a00-951d-11eb-8baf-456717e5670a.png): all monsters "gain" skill points no matter what you do. It should probably be "allocating", "spending", or "using"
* [too much spreading](https://user-images.githubusercontent.com/35816592/113508320-5524d700-951d-11eb-8283-6c34320a29ab.png). 
* [i heard the bandits in captivity](https://user-images.githubusercontent.com/35816592/113508368-9f0dbd00-951d-11eb-819d-1354410e5cc9.png) -> i heard the bandits are in captivity
* [Great Log's Key](https://user-images.githubusercontent.com/35816592/113509463-b8b20300-9523-11eb-8cc3-7de039a18ade.png) is called Great Log Key in the Item Sack.
*  I remember an npc in Asyia/Asiya saying "traveling" (or "travelin'") to be immediately followed by "travelling" (or traveller?) the next line. Double Ls are typically British, while the single L is typically American. I was thinking that Dragon Quest localizations often have different accents, so it might be excused, but this was literally two successive lines from a single character. Most existing instances I've seen seem to use a single L
* [even in trouble](https://user-images.githubusercontent.com/35816592/113517311-232b6900-954d-11eb-9ae5-ac11104ef20a.png) -> ever in trouble

The rest might less strictly be considered errors and more (odd) English stylistic choices:

* Sometimes certain Words [switch](https://user-images.githubusercontent.com/35816592/113509079-9c14cb80-9521-11eb-9867-c2492cf36f20.png) between being capitalized and lowercase at seemingly random. Now I'm sure this done consistently with how the Japanese writes some《Words》, but this isn't really done in English. For most of Words, I would probably favor getting rid of the capitalization, provided that they're not special names, selectable menu entries, at the start of sentences, etc.
  * e.g. [Today](https://user-images.githubusercontent.com/35816592/113506370-77fdbe00-9512-11eb-858d-e85e53a19b14.png), yer [Brother](https://user-images.githubusercontent.com/35816592/113515580-549f3700-9543-11eb-9105-6f2d4084bb20.png)/Sister, [Waves](https://user-images.githubusercontent.com/35816592/113516075-58808880-9546-11eb-9007-2691ffafcdda.png), Gold, Gender, Scout, Inn, Bandits, City, Castle, Circus, Troupe, Lake, Guards, Aqueduct
  * [Pirate Key](https://user-images.githubusercontent.com/35816592/113509622-a2f10d80-9524-11eb-8f93-bfd93b3d15fb.png)
 vs [Pirate key](https://user-images.githubusercontent.com/35816592/113509634-ae443900-9524-11eb-80d3-76718f8be1a8.png)
  * I've seen both "His Majesty" and his Majesty". I'm not aware of any reason to use one over the other, but I think capitalization of "His" should be consistent either way
  * I've also seen many variations of Other World, other worlds, Other worlds, Other Worlds, etc. that I feel should be made consistent in most (possibly not all) cases.
  * Also some capitalized words after commas that should be lowercased: e.g. [Oh, Poor thing](https://user-images.githubusercontent.com/35816592/113507176-e9d80680-9516-11eb-8f78-0a99335dd09c.png) -> Oh, poor thing, [Wah, It's](https://user-images.githubusercontent.com/35816592/113516027-0b9cb200-9546-11eb-9b0e-38c0e3abbfaa.png) -> Wah, it's

* Commas and other punctuation strangeness。Same as before、mostly likely from maintaining the positions of Japanese commas。
  * [line](https://user-images.githubusercontent.com/35816592/113505963-ebea9700-950f-11eb-8d15-dd09140a6c3e.png) "Now that you have some treasure" should be separated from "let's head deeper inside", possibly with a comma. "Now that" is an odd place to put an ellipsis after too, so I would just move it to be after "treasure" instead.
  * unnecessary commas: [1](https://user-images.githubusercontent.com/35816592/113506386-9bc10400-9512-11eb-930a-c269c734233f.png), [2](https://user-images.githubusercontent.com/35816592/113508419-e5fbb280-951d-11eb-9099-6a008059a69c.png)
  * [no comma needed here either](https://user-images.githubusercontent.com/35816592/113506470-1853e280-9513-11eb-8c81-5cd74d66a8a0.png), but maybe this could be rewritten to something like "'Tis I, Grandpa Medal", or "It is I, Grandpa Medal" 
  * [another one](https://user-images.githubusercontent.com/35816592/113507833-c0b97500-951a-11eb-8b63-4a398e7f44e7.png): either "His Majesty has returned!" or "His Majesty, he's returned!"

* [Slime-type some](https://user-images.githubusercontent.com/35816592/113506669-3a019980-9514-11eb-8450-78756dbd37af.png): this confused me when I read it, and thought it was supposed to meant "some Slime-type monsters" (so not metal slimes, etc.) I didn't understand until I saw other weapons with [family]-type [amount]. I think "[family]-type***s*** [amount]" would be less confusing. But if this is how previous entries word it (didn't check), fair enough.
  * Also, [unlike all the other weapons in the shop](https://user-images.githubusercontent.com/35816592/113515268-6e3f7f00-9541-11eb-9e84-b343ab86e56c.png), the second word isn't capitalized

**Comment by dackst** [comment]
post-desert:

- ["who's family"](https://user-images.githubusercontent.com/35816592/114359401-e9a4c000-9b41-11eb-812a-c3449381aad3.png) should be "***whose*** family"
- ["Metorite"](https://user-images.githubusercontent.com/35816592/114360501-15747580-9b43-11eb-8b41-079e5aedf238.png) should be spelled Met***e***orite
- [tournement](https://user-images.githubusercontent.com/35816592/114360743-5e2c2e80-9b43-11eb-8d73-c66b9c05ef77.png) -> tourn***a***ment
- what's a [grand](https://user-images.githubusercontent.com/35816592/114360879-874cbf00-9b43-11eb-87b7-cd0de1b46eca.png)?
- [parents strength](https://user-images.githubusercontent.com/35816592/114361031-b5ca9a00-9b43-11eb-821f-8f64c4c46b2b.png) => parents' strength
- [exhilirating](https://user-images.githubusercontent.com/35816592/114361235-e579a200-9b43-11eb-8bec-ef2ff31e0031.png) -> exhil***a***rating
- [meteorite showers](https://user-images.githubusercontent.com/35816592/114361323-004c1680-9b44-11eb-8e70-a4ccdb6ad3b9.png) aren't a thing. Meteors/shooting stars are only called meteorites if/when they hit the ground. 
  - I feel like this is also applicable to every other instance of "meteorite" I've seen so far. For reference, both DWM2 on GBC and the fan translation of Terry's Wonderland 3D use "Starry Shrine" and "Starry Night Tournament" instead of "[Mm]eteorite [Ss]hrine" and "[Mm]eteorite [Tt]ournament"
- [Tara's the one who's entering the tournament, not you.](https://user-images.githubusercontent.com/35816592/114362825-c714a600-9b45-11eb-83a6-8bd599320fbf.png)
- [man that appears to be](https://user-images.githubusercontent.com/35816592/114362993-f3302700-9b45-11eb-961c-253785ee3648.png) -> man that ***he*** appears to be
- [after get a hold of the bell](https://user-images.githubusercontent.com/35816592/114363327-47d3a200-9b46-11eb-941c-97443d4e708c.png) -> after ***he got*** a hold of the bell? after ***getting*** a hold of the bell?
- [I don't know what this is supposed to mean](https://user-images.githubusercontent.com/35816592/114363534-7c475e00-9b46-11eb-9aaf-3837ad60d6f6.png). There's monsters ***outside*** of the hut that ***I*** can fight, and it doesn't seem like I need to do so to reach the pyramid
- [alongside](https://user-images.githubusercontent.com/35816592/114364203-29ba7180-9b47-11eb-9faa-870e3f6663e1.png) is one word
- [the arena isn't a farm](https://user-images.githubusercontent.com/35816592/114365074-13f97c00-9b48-11eb-9165-2dd4f34f6a85.png). I was expecting a second monster farm on the island or something
- [No matter what you tell me, you seem wrong. This sentence...](https://user-images.githubusercontent.com/35816592/114365277-5622bd80-9b48-11eb-8083-7e224be935fb.png)
- So I finally ran into a "[Drak Slime](https://user-images.githubusercontent.com/35816592/114367568-8ff4c380-9b4a-11eb-986d-5cf694ba4057.png)" in the gameplay, which conflicts with the "[Drake slime](https://user-images.githubusercontent.com/35816592/113515680-f9217900-9543-11eb-831d-d0b037b2179e.png)" I brought up earlier from the intro
- [town](https://user-images.githubusercontent.com/35816592/114370607-ac462f80-9b4d-11eb-9d72-832732519efa.png) -> town***s***
- [good](https://user-images.githubusercontent.com/35816592/114370733-c97afe00-9b4d-11eb-8114-f6af94501fcb.png) -> good***s***


water world:

- [were](https://user-images.githubusercontent.com/35816592/114365984-fed11d00-9b48-11eb-96ec-dc518a24732b.png) -> we're
- the volcano doesn't appear to be in a lake? unless this whole world is in a lake and not a sea? [1](https://user-images.githubusercontent.com/35816592/114366256-448de580-9b49-11eb-9bbb-837431a7a3cd.png), [2](https://user-images.githubusercontent.com/35816592/114368650-9899c980-9b4b-11eb-823a-df9bc70efafa.png)
- [a far](https://user-images.githubusercontent.com/35816592/114366342-5c656980-9b49-11eb-986f-e69aeeeb67f9.png) -> afar
  - also another instance of "travelled" with two Ls
- [if who had an appealing singing voice, old man?](https://user-images.githubusercontent.com/35816592/114366822-cc73ef80-9b49-11eb-9b4d-f35e685baadd.png)
- the squid is referred to as [female](https://user-images.githubusercontent.com/35816592/114377575-cd5e4e80-9b54-11eb-9c9a-0f57b84d1346.png), but it's actually [male](https://user-images.githubusercontent.com/35816592/114377530-bfa8c900-9b54-11eb-8af1-3a0311e2e034.png) when it joins you?
- [mainland](https://user-images.githubusercontent.com/35816592/114368407-638d7700-9b4b-11eb-9ed2-7dad809b14bf.png) is one word
- [water levels fall](https://user-images.githubusercontent.com/35816592/114368917-de569200-9b4b-11eb-86ac-2e65164258ca.png): given that restoring the lighthouse has always made it so the rocks in the water no longer block your way, I feel like this should probably say "the water levels'll ***rise***"
   - [later dialogue](https://user-images.githubusercontent.com/35816592/114850815-27f2e700-9daf-11eb-8dd0-35c6348bf95f.png) seems to support that water levels rose rather than fell

- [Moonstone was keep](https://user-images.githubusercontent.com/35816592/114369262-32617680-9b4c-11eb-8909-5435a036aa3e.png) -> Moonstone was ***kept***
- [pirates](https://user-images.githubusercontent.com/35816592/114369911-dea35d00-9b4c-11eb-9561-733e59e08213.png) -> pirates'? pirate?
- Moonstone vs. [Moon Stone](https://user-images.githubusercontent.com/35816592/114371505-8d946880-9b4e-11eb-8cb1-16dfd460acd6.png)
- [lucky that I run into you](https://user-images.githubusercontent.com/35816592/114371688-bf0d3400-9b4e-11eb-8577-c645c7f4a824.png) -> "lucky that I r***a***n into you". Also the comma after "bar" is unnecessary
- [was returned by there are still](https://user-images.githubusercontent.com/35816592/114853398-bd8f7600-9db1-11eb-9904-5f892cd8aa6b.png) -> was ****returned, but*** there are still


more great log stuff:
- [I'm was](https://user-images.githubusercontent.com/35816592/114848507-c2056000-9dac-11eb-9900-8d2e2f03bd97.png) (I am was?) -> I was
- [weapen](https://user-images.githubusercontent.com/35816592/114848663-eb25f080-9dac-11eb-84f3-6e9dbc4e6726.png) -> weap***o***n
- [banced](https://user-images.githubusercontent.com/35816592/114848768-0bee4600-9dad-11eb-88a3-e8485a3b2a38.png) -> ba***la***nced
- [developer](https://user-images.githubusercontent.com/35816592/114848851-27595100-9dad-11eb-89dc-37d772d43a9e.png) -> develop
- [meaneuvers](https://user-images.githubusercontent.com/35816592/114849955-4b696200-9dae-11eb-93ca-7f157be75a7b.png) -> maneuver***ing***
- [monsters](https://user-images.githubusercontent.com/35816592/114850063-63d97c80-9dae-11eb-9556-fdd25260b10c.png) -> monster***'***s
- [walkway](https://user-images.githubusercontent.com/35816592/114855145-9f2a7a00-9db3-11eb-8673-e94e51f9d4fa.png) -> walkway

- [encounted](https://user-images.githubusercontent.com/35816592/114848979-4a840080-9dad-11eb-8f9f-c30ffd7cf4db.png) -> encoun**ter**ed, StreetPassed -> StreetPass
- [Pschyes](https://user-images.githubusercontent.com/35816592/114849115-730bfa80-9dad-11eb-9932-d180f43c05ba.png) -> Psyches
- [You peacefully view](https://user-images.githubusercontent.com/35816592/114849231-8e770580-9dad-11eb-90f6-56f509047a60.png) -> You ***can*** peacefully view
- [Chimera](https://user-images.githubusercontent.com/35816592/114849388-afd7f180-9dad-11eb-9d78-e728cf538e9b.png) -> Chim***a***era, to match the [monster](https://user-images.githubusercontent.com/35816592/114849512-d302a100-9dad-11eb-852c-ce46f714ef55.png)
- [it'll get a book](https://user-images.githubusercontent.com/35816592/114849678-fd545e80-9dad-11eb-914d-9571ef4bba11.png): based on his [earlier dialogue](https://user-images.githubusercontent.com/35816592/114851003-5cff3980-9daf-11eb-8c93-c4b90e1c7ad4.png), I assume he talking about himself, so it should be "***I'll*** get a book"
- [easyi](https://user-images.githubusercontent.com/35816592/114851228-9b94f400-9daf-11eb-96b9-636686777d15.png) -> easy
- [Princes's](https://user-images.githubusercontent.com/35816592/114851308-b23b4b00-9daf-11eb-97e1-d9b9a7ede00a.png) -> Prince's
- [can't open my shop having traveled](https://user-images.githubusercontent.com/35816592/114851415-d008b000-9daf-11eb-83bd-62bac2c978f0.png): I think it should be "can't open my shop ***after*** having traveled"?
- [wind blows to the island from here](https://user-images.githubusercontent.com/35816592/114851561-f9c1d700-9daf-11eb-8b1e-3fde7297193d.png): Where is this "the island" if not "here"? Maybe "blows to this here island"?
- [I'll make 'em laugh if I'm the butt of their joke next](https://user-images.githubusercontent.com/35816592/114851953-545b3300-9db0-11eb-8901-fa9156752d1c.png) - I feel like there's some idiom being mistranslated here. No one likes Kameha's pranks, but "I'll make 'em laugh" almost seems to suggest otherwise, and that this guy willingly subjects himself to them. Maybe "I'll show them"?
  - https://www.macmillandictionary.com/us/dictionary/american/i-ll-show-you-him-them-etc
  - https://www.collinsdictionary.com/us/dictionary/english/ill-show-you
- [what can you catch any](https://user-images.githubusercontent.com/35816592/114852768-14e11680-9db1-11eb-8c4b-9c2e08a72718.png): either "can you catch any" or "what can you catch"
- [y'knov](https://user-images.githubusercontent.com/35816592/114853034-612c5680-9db1-11eb-9aec-f084b442c55f.png) -> y'kno***w***
- [Ice key](https://user-images.githubusercontent.com/35816592/114853242-96d13f80-9db1-11eb-9740-c72282eee8ed.png) -> Ice ***K***ey?
- [Slime types monsters are pretty common through out](https://user-images.githubusercontent.com/35816592/114853932-4c9c8e00-9db2-11eb-8c3e-6f1292cd586f.png) -> ***Slime-type*** monsters are pretty common ***throughout***
- weird pluralization: [1](https://user-images.githubusercontent.com/35816592/114854107-7786e200-9db2-11eb-8f2b-af4612cc0022.png), [2](https://user-images.githubusercontent.com/35816592/114854429-cf254d80-9db2-11eb-999a-7305b373e4e0.png)
- [the monsters in your party](https://user-images.githubusercontent.com/35816592/114854202-938a8380-9db2-11eb-99c9-ee422299f121.png): he only asked for one monster here
- [The Monster](https://user-images.githubusercontent.com/35816592/114854493-e2d0b400-9db2-11eb-8e68-c59298dca600.png) -> The monsters (there's multiple monsters here)
- use a comma or ellipsis, but not both: [1](https://user-images.githubusercontent.com/35816592/114854765-288d7c80-9db3-11eb-92c2-99cb7acb6536.png), [2](https://user-images.githubusercontent.com/35816592/114854738-23c8c880-9db3-11eb-80cb-a1c630dcddbb.png)
- [lemonade!".](https://user-images.githubusercontent.com/35816592/114855247-bcf7df00-9db3-11eb-9f0f-42d7dd39438c.png): you can also place ending punctuation either inside or outside the quotes, but not both



































overflows:
- [sandstorm](https://user-images.githubusercontent.com/35816592/114363225-312d4b00-9b46-11eb-97d7-1a9ae72e8f39.png)
- [slightly too much text](https://user-images.githubusercontent.com/35816592/114364563-83bb3700-9b47-11eb-9f7b-c24f9d3417dd.png)
- [farm](https://user-images.githubusercontent.com/35816592/114370392-6c7f4800-9b4d-11eb-9c9c-76fbbb0cf1c7.png)




Comma shenanigans:
- unnecessary commas:
  - [new feature that will allow you](https://user-images.githubusercontent.com/35816592/114363993-f7107900-9b46-11eb-8612-fc98ad62c784.png)
  - [swap party members in those saved parties to help save some time](https://user-images.githubusercontent.com/35816592/114364120-15767480-9b47-11eb-8532-2ad79dea2995.png)
  - [ocean is vast as it is deep](https://user-images.githubusercontent.com/35816592/114367122-1e1c7a00-9b4a-11eb-945a-58f55474a900.png)
  - [somewhere in the southwestern regions of our world resides](https://user-images.githubusercontent.com/35816592/114368168-24f7bc80-9b4b-11eb-8dae-7bab4a16210d.png)
  - [to realize its true power were those nasty pirates](https://user-images.githubusercontent.com/35816592/114370948-0646f500-9b4e-11eb-894a-e715ecb44e1d.png)






- missing commas
  - [whatever happens, I'm happy](https://user-images.githubusercontent.com/35816592/114364331-49519a00-9b47-11eb-8434-f9684858e3ee.png)
  - [that said, sometimes you get lucky](https://user-images.githubusercontent.com/35816592/114364829-ce3cb380-9b47-11eb-9b6c-f179412d5f39.png)
  - [you're a girl, so I guess that's okay](https://user-images.githubusercontent.com/35816592/114364972-f6c4ad80-9b47-11eb-8eb8-ed6060c02f6d.png)
  - [like your life depends on it, my small friend](https://user-images.githubusercontent.com/35816592/114366721-b2d2a800-9b49-11eb-98d8-be03a6d873a7.png)
  - [As one who lives in the seas, I'm deeply grateful](https://user-images.githubusercontent.com/35816592/114371403-72c1f400-9b4e-11eb-8d77-0096b8e034bb.png)
  - [wasn't any good, so you're](https://user-images.githubusercontent.com/35816592/114852726-098deb00-9db1-11eb-9583-457d4ac28b4e.png)
  - [Who am I kidding, I can't lie](https://user-images.githubusercontent.com/35816592/114853828-31318300-9db2-11eb-8794-0ba49b7b76d9.png)
  - [when she's pleased with me, so I'm gonna do my best](https://user-images.githubusercontent.com/35816592/114854313-aef58e80-9db2-11eb-82e7-2102a965a5f0.png)

**Comment by Ich73** [comment]
> [Tara's the one who's entering the tournament, not you.](https://user-images.githubusercontent.com/35816592/114362825-c714a600-9b45-11eb-83a6-8bd599320fbf.png)

What would you change the line to?

**Comment by dackst** [comment]
> > [Tara's the one who's entering the tournament, not you.](https://user-images.githubusercontent.com/35816592/114362825-c714a600-9b45-11eb-83a6-8bd599320fbf.png)
> 
> What would you change the line to?

Probably either "I'll need to enter ***you*** into the children's tournament", or "***you'll*** need to enter into the children's tournament".
