### ISSUE TITLE
Wrong text in popup when earning some new titles

### ISSUE THREAD

**Issue by mdraves91** [Ich73/DQM2-FanTranslation#14]
The text in the popup that the game shows when you earn a new title is incorrect for some of them.

When I scouted my second **Material** monster, I earned the 'Pebble' title, but the pop-up description said I had scouted 2 from the **Beast** family. 
![2021-04-04_10-01-09 301_top](https://user-images.githubusercontent.com/1939553/113514972-4519f100-9537-11eb-952f-3e984b2c1ae4.png)

The text is correct if you check the title in the Archive menu.
![2021-04-04_10-06-59 653_top](https://user-images.githubusercontent.com/1939553/113514973-46e3b480-9537-11eb-8c7e-8f95fa341d14.png)

The same thing happened with two other titles: 
Scouting 2 nature popped up as 2 material
Scouting 2 beast popped up as 2 nature

The rest of the titles for scouting two monsters of a family are correct (I have not scouted a second ??? monster yet though).

**Comment by mdraves91** [comment]
Found one more that is incorrect:
![2021-04-04_12-48-52 260_top](https://user-images.githubusercontent.com/1939553/113518661-5a017f00-954d-11eb-90ab-41ca03f26e5f.png)

**Comment by Ich73** [comment]
I just checked: Beast, Nature and Material Families got mixed up in those messages.

**Comment by Ich73** [comment]
If you're using a LayeredFS patch, you can now [update your workspace](https://github.com/Ich73/DQM2-FanTranslation/wiki/Installing-LayeredFS#update-workspace) using the UW script.
