### ISSUE TITLE
Crash in Wifi Lobby, after Challenge Cup rule display / During B-Rank arena / and more

### ISSUE THREAD

**Issue by Clydefrosch22** [Ich73/DQM2-FanTranslation#15]
Just had the system randomly crash on me in the Wifi Lobby.
After going to the challenge cup I was sitting on the new rule screen for a minute while using google lense to translate the current rule. Then I just hit B to leave and that's where it happened.
Tried again without it crashing, but also didn't wait on the rule screen as long this time. Just to be safe, here's a dump.

[crash_dump_00000131.zip](https://github.com/Ich73/DQM2-FanTranslation/files/6260343/crash_dump_00000131.zip)

Edit: Crashed in the wifi lobby again today, this time while talking to the bunny girl.

**Comment by Clydefrosch22** [comment]
[crash_dump_00000132.zip](https://github.com/Ich73/DQM2-FanTranslation/files/6266840/crash_dump_00000132.zip)
Had a second one right before the start of the 3rd battle of B-Rank arena.

**Comment by Clydefrosch22** [comment]
and one more, this time it happened while shutting down the game (home menu > x button)
[crash_dump_00000133.zip](https://github.com/Ich73/DQM2-FanTranslation/files/6290892/crash_dump_00000133.zip)

**Comment by Ich73** [comment]
I don't see how our translation could cause such crashes, and I haven't heard of anyone else encountering similar problems.
Maybe it has to do with your setup, e.g. other apps like NTR plugins or streaming apps. I've had some crashes with those myself.
I'm afraid, I cannot help here. I will close this issue for now, but feel free to reopen it.
