### ISSUE TITLE
Text error in the Thaumatosarus quest

### ISSUE THREAD

**Issue by Animefan8451** [Ich73/DQM2-FanTranslation#16]
![citra-qt_sPJWFvn3wI](https://user-images.githubusercontent.com/82116402/113916726-515bb380-97ae-11eb-9875-dac122f25d3d.png)

**Comment by Ich73** [comment]
If you're using a LayeredFS patch, you can now [update your workspace](https://github.com/Ich73/DQM2-FanTranslation/wiki/Installing-LayeredFS#update-workspace) using the UW script.
