### ISSUE TITLE
.e Files

### ISSUE THREAD

**Issue by Colmines92** [Ich73/DQM2-FanTranslation#2]
I've been going through the .e files and found that they are actually GZip files that can be opened with 7-zip. Inside they contain the file with the event data. Using your BinJEditor tables I can see the dialogs, however, I can't find the logic for all the bytes before the dialogs, since they don't have the offset structure, or offset-size.
You may want to take a look at it to see if you can figure out the logic of that.

I don't speak English so you can expect some inconsistencies in my posts.

**Comment by Ich73** [comment]
I found that out as well. They are gzip compressed, use the same decoding table as binJ files and separate texts with the same separator token. I also found out that there is a 4-byte group specifying some sort of length of the text right before the text starts. So I can extract all the texts from e files, but as you said there are a lot of additional bytes where some of them have to be changed as well when you want to insert new text. If you want to insert texts with fewer letters there is a workaround but for longer texts you need to change those bytes.

**Comment by Colmines92** [comment]
Haven't you tried contacting the Terry Wonderland translation team to see what tool they used and if there is any chance of getting it?

**Comment by Ich73** [comment]
I haven't contacted them myself but they stated pretty clearly that they are not willing to share their tools.

**Comment by Ich73** [comment]
If you want to help decyphering e files, contact me directly on Discord [(*)](https://discord.com/channels/@me/Dominik#9803/).

**Comment by Colmines92** [comment]
Check the Discord link, it sends me to my own profile.

**Comment by Ich73** [comment]
Just add me: Dominik#9803

**Comment by Colmines92** [comment]
I found the text lengths!!!
Now we just need to test it.
Come to Discord.
