### ISSUE TITLE
Empty lines

### ISSUE THREAD

**Issue by dackst** [Ich73/DQM2-FanTranslation#20]
There are some lines in the English event script that are empty, but have text in the Japanese:

- line 59 of `CTC01`
- line 22 of `DTA02`
- line 88 of `DTC01`
- line 120 of `MAA04`
- line 49 of `ADD03`

Not sure if this is intentional.

**Comment by Ich73** [comment]
I also noticed:
  * line 768 and 769 of `msg_key`
  * line 24 of `CTE02`

I will compare with our script to check if this is correct.
