### ISSUE TITLE
Small translation issues on some boss monsters

### ISSUE THREAD

**Issue by Bunni89** [Ich73/DQM2-FanTranslation#21]
Hello, I'm so sorry to nitpick about a small detail like this! I just want to first say a huge thank you for translating the game, I've been having so much fun playing it, it's so wholesome and fun! And with a whole 800 monsters it must have been extremely hard to fact check translations for returning cameos like this, so I hope i don't sound ungrateful for all the effort you've put into the project. Thank you so much for being extremely awesome!!

First issue I noticed is that the names are the wrong way round for Mortamor's forms. His first form has his Japanese name, when it should be "Mortamor 1"
![Screenshot_20210415-203223~2](https://user-images.githubusercontent.com/82721454/115119715-b929af80-9fa1-11eb-834b-50285d6748de.png)
And then Mortamor 2 is correct, but the one that's just called Mortamor should be Mortamor 3.

And then I was kind of confused by Dr Snapped's archive description seeming out of character? 
![EzD_RunWYAANYox](https://user-images.githubusercontent.com/82721454/115119836-58e73d80-9fa2-11eb-859e-a22cad25f8cc.jpeg)
It says he regrets turning into a monster, when in the original game he came from (DQMJ1) he was all "yay, I'm a monster!" and the entire reason you had to fight him is cos he was so happy about being a monster that he wanted to turn everyone into monsters too. He was kind of a weird character, so I can totes understand why that kind of personality wouldn't exactly be the first thing you'd expect. (Though the uniqueness factor of a random old man being hyped to become a demon lord was why he became my fave character, lol...)

I tried running the Japanese character profile through Google translate and it seems to be similar to the one he had in previous games? 
![Screenshot_20210416-040942](https://user-images.githubusercontent.com/82721454/115119951-d6ab4900-9fa2-11eb-949b-b6d46770626e.png)
The DQMJ3 fan translation had it as "his form is scary but his mood remains cheerful". So pretty much "he became a monster and doesn't regret it", so I can totally see how that might have got mixed up?

Sorry if this is a silly nitpick! I don't mean to be rude. And I'm sorry if I didn't explain it well. It's also completely possible that I might be wrong here, and maybe the character's profile just changed in this new game? (I think i would die of embarassment for wasting your time, haha!)

I wanna once again say thanks for all your good work and I'm having a blast with the game! I love how professional your translation sounds and how all the characters have their own distinct mannerisms and lots of adorable puns for all the monsters that talk on your farm! And "Montner" was such a great name choice! I'm also glad to see "Rottney and Cortney" return because that was my favourite name pun in the previous game and I wish that it could be canon! It suits them perfectly!

**Comment by Ich73** [comment]
No worries, we welcome all kinds of small corrections.
We renamed the Martamors accordingly and also renamed their Skill to Mortamor.
Thanks for your kind words too.

**Comment by Ich73** [comment]
If you're using a LayeredFS patch, you can now [update your workspace](https://github.com/Ich73/DQM2-FanTranslation/wiki/Installing-LayeredFS#update-workspace) using the UW script.
