### ISSUE TITLE
More text corrections and such 

### ISSUE THREAD

**Issue by Clydefrosch22** [Ich73/DQM2-FanTranslation#24]
Ok, here's the next batch
https://imgur.com/a/7m53OEH

**Comment by Clydefrosch22** [comment]
The bunnygirl scouts say 

"Wait, you're are a SCOUT!?"

and after winning,

"You really CAN really fight after all..."

second one might be fine if they're meant to be like... a bit stupid?

**Comment by Clydefrosch22** [comment]
This is just a general question, but 'Gloom' is 'The Taker of Light', right?

Is 'The Potentate of Portals' also just another name for Gloom? 
The heroes occasionally just talk about the Potentate and at first I thought he was some kind of underling of gloom, but now it seems more like it also is a different name for him.
Maybe this could be made clearer in the dialogue when the Potentate is first mentioned?


edit: and now Miraclea also calls him the King of Darkness. Is this possibly meant to be a running gag?

**Comment by Clydefrosch22** [comment]
After the final boss, Rottney says something like Twiney was a

'royal pain in then butt'

skipped the text too fast, but there can't be too many lines with butt in them

**Comment by Clydefrosch22** [comment]
https://imgur.com/a/YLHTA53

**Comment by Clydefrosch22** [comment]
and one more 
https://imgur.com/a/Fv2Uajq

i have about 50 more screenshots and still need to do every event battle, but i'm not sure if i'll get around to them in the next days

**Comment by Clydefrosch22** [comment]
ok, i did the remaining screenshots i had, but there's still more event battles. someone on discord already mentioned there might be something off with later ones.

https://imgur.com/a/BJjTt7G

**Comment by Clydefrosch22** [comment]
i just noticed, at times the word scout is capitalized and at times, it is not.

this is from the female warrior scout
"How are you a scout? Hmph... they lust let anyone be a
scout these days."

also, after you beat her and get a weapon, i think it said
"Tara found the Metal Claws"

that should probably be 'got'

**Comment by Clydefrosch22** [comment]
The bookcase for SS Rank monsters has a line going over the box once you befriended 30 SS-Rank Monsters

didn't manage to make a snapshot in time though, it's the line before 
"And now I'll give you the key that will let you meet and
befriend SS-Rank monsters."

**Comment by Clydefrosch22** [comment]
https://imgur.com/a/T3W9HnM

here's more

Edit: Just noticing, the lines about Super Giga Bodies, they should probably say Ultra Body, like the trait is actually called.

**Comment by Clydefrosch22** [comment]
and one more
https://imgur.com/a/bWG438l

**Comment by dackst** [comment]
on "right, honorable": https://en.wikipedia.org/wiki/The_Right_Honourable

the comma probably isn't needed, and the mixing of British and American English is a little weird, but it's a thing.

**Comment by Ich73** [comment]
@Clydefrosch22 Thanks for all your efforts in submitting these issues!
