### ISSUE TITLE
text stuff (snow through limbo)

### ISSUE THREAD

**Issue by dackst** [Ich73/DQM2-FanTranslation#26]
I wasn't sceenshoting things nearly as often as in the first world, so they're combined together. Most of these don't seem to be already fixed or previously reported.

- [when there are more than ★](https://user-images.githubusercontent.com/35816592/117429210-cf69c200-aef4-11eb-8a3f-4b41a8719840.png): when there are more than one ★? when there are more ★s?
- [soldiers morale](https://user-images.githubusercontent.com/35816592/117430119-c4636180-aef5-11eb-8d22-b14bfe7835ae.png) -> soldier's morale
- [setup a blockade](https://user-images.githubusercontent.com/35816592/117430496-33d95100-aef6-11eb-8c88-c60aad7ee760.png): "setup" is the noun, [the verb is "set up"](https://en.wiktionary.org/wiki/setup#Verb)
- [youself](https://user-images.githubusercontent.com/35816592/117431638-77808a80-aef7-11eb-8f7d-b249910088c5.png) -> you**r**self
- [you've come...didn't you?](https://user-images.githubusercontent.com/35816592/117431884-bca4bc80-aef7-11eb-9c88-52280900dc8c.png): I think it should probably be "haven't you" to match up with the beginning of the sentence
- [allow](https://user-images.githubusercontent.com/35816592/117432924-e6121800-aef8-11eb-9fc5-78f381314392.png) -> allows, maybe? It doesn't seem to be part of the accent.
- [I like girls that are bubbly and energetic](https://user-images.githubusercontent.com/35816592/117433745-d1824f80-aef9-11eb-8a07-89be7604de19.png): maybe the Japanese stereotype is slightly different, but my understanding of a "tomboy" often includes being (at least physically) energetic.
- [this must too be a test](https://user-images.githubusercontent.com/35816592/117434253-70a74700-aefa-11eb-8f2c-e8bb6d2a17a0.png) -> this too must be a test
- [An doll](https://user-images.githubusercontent.com/35816592/117434665-f62af700-aefa-11eb-92a6-c563213f7459.png) -> A doll
- There is an instance of "sonya" that should be capitalized I forgot to screenshot.
- [Everyone know's](https://user-images.githubusercontent.com/35816592/117435549-fb3c7600-aefb-11eb-9bf8-8a0194f07486.png) -> Everyone knows
- [she had awakens](https://user-images.githubusercontent.com/35816592/117435634-10190980-aefc-11eb-9230-38564644c77b.png) -> she awakens?
- [knocked me within seconds](https://user-images.githubusercontent.com/35816592/117435870-52424b00-aefc-11eb-8394-aa1b19c76a4e.png): probably should be "knocked me out within seconds"
- [from to the North](https://user-images.githubusercontent.com/35816592/117436127-a0574e80-aefc-11eb-976a-bb264f27d600.png) -> probably should be "from the North", maybe "to the North" but not both.
- [Haawwgry](https://user-images.githubusercontent.com/35816592/117436270-ced52980-aefc-11eb-9087-dd965da2cdb0.png): This is one of the lines that was [previously empty](https://user-images.githubusercontent.com/35816592/117437351-0db7af00-aefe-11eb-9c7c-9be8a9eb9f8d.png), but it still doesn't make much sense. I assume it should be some sleeping noise, maybe some kind of snoring, heaving breathing, or mumbling.
- [doesn't like look well](https://user-images.githubusercontent.com/35816592/117437864-cd0c6580-aefe-11eb-884d-cacf26d9c825.png): doesn't look too well? doesn't look like it's well? doesn't look well?
- [my honey send me a package](https://user-images.githubusercontent.com/35816592/117438099-16f54b80-aeff-11eb-9ebb-9dd9c26974e9.png): either "my honey is sending me a package" or "my honey sent me a package"
- [That reminds me when my Queen met with her illness we also stopped](https://user-images.githubusercontent.com/35816592/117439224-959eb880-af00-11eb-8f61-4b75e41362bd.png) -> That reminds me, when my Queen met with her illness, we also stopped
- [If you wish to travel to the throne room I can guide you there now.](https://user-images.githubusercontent.com/35816592/117441232-11016980-af03-11eb-8fbb-bc259e4e47db.png) -> If you wish to travel to the throne room, I can guide you there now.
- [horse and slime](https://user-images.githubusercontent.com/35816592/117453678-38603280-af13-11eb-93ef-3a9b4dac55c7.png): based on the [surrounding](https://user-images.githubusercontent.com/35816592/117453900-79f0dd80-af13-11eb-94bc-eb4ed5d495b2.png) [dialogue](https://user-images.githubusercontent.com/35816592/117453908-7d846480-af13-11eb-829d-fd609e9029eb.png), the slime is supposed to have been the one that was feeling lonely, and the horse brought **it** here, rather than the other way around.
- [I don't know what "before then" is supposed to mean.](https://user-images.githubusercontent.com/35816592/117442054-4195d300-af04-11eb-863b-c95d7c5a7618.png) It could be removed entirely, or changed to something like "Unlike before, my liege has listened to our views like a completely changed man." or "My liege has listened to our views like a completely changed man from before."
- [The monsters in front of your house are](https://user-images.githubusercontent.com/35816592/117442445-c385fc00-af04-11eb-8dd5-093c0a2fa2fc.png): based on the [next line](https://user-images.githubusercontent.com/35816592/117442509-dc8ead00-af04-11eb-9c61-1e8027db06a0.png), I assume it's talking the Montner, and instead should be something like "The **monster** in front of your house **is**". There isn't any reason to think slimes and cactiballs are particularly strange.
- [parculiar](https://user-images.githubusercontent.com/35816592/117454118-c4725a00-af13-11eb-8514-82aa5d728d58.png) -> peculiar
- [Isn't true](https://user-images.githubusercontent.com/35816592/117454360-0ef3d680-af14-11eb-953a-b19bd80e3c75.png) -> Isn't **it** true

- [What do you think a child like you can do?](https://user-images.githubusercontent.com/35816592/117443072-9be36380-af05-11eb-9ef6-bbba11c5a976.png): I think it would make more sense if it was instead "What does he think a child like you can do?" The sage is the only reason the player character can do anything at this point.
- [The Hades condor's roost in the westlands.](https://user-images.githubusercontent.com/35816592/117444398-6a6b9780-af07-11eb-9838-590572ce6c1a.png): "roost" can be both a noun and (in this case, plural) verb, while "condor's" is singular and possessive. I'm thinking this should probably be "The Hades condors roost in the westlands". It could also be "The Hades condors' roost is in the westlands.", "The Hades condor roosts in the westlands.", or "The Hades condor's roost is in the westlands."
- [Some say there were these so-called "angels" in our world had something to do with 'em](https://user-images.githubusercontent.com/35816592/117447460-8d984600-af0b-11eb-956b-e345dd229ad4.png): either "Some say there were these so-called "angels" in our world **that** had something to do with 'em" or "Some say ~~there were~~ these so-called "angels" in our world had something to do with 'em"
- [The Light Orb has already. Fallen from the Hades condor's clutches](https://user-images.githubusercontent.com/35816592/117447842-026b8000-af0c-11eb-9494-9052bd67c73d.png) -> The Light Orb has alread**y f**allen from the Hades condor's clutches
- [Celestial Goblet - incredible staff](https://user-images.githubusercontent.com/35816592/117451226-3ba5ef00-af10-11eb-844c-0384e47e8a0a.png): I can't find any use of the word [staff](https://en.wiktionary.org/wiki/staff) that overlaps with the word [goblet](https://en.wiktionary.org/wiki/goblet). By [the graphics](https://user-images.githubusercontent.com/35816592/117451507-9b9c9580-af10-11eb-99ed-a424ea3ca7e3.png), it seems to looks more like a goblet.
- [Why is this one guard acting especially haughty?](https://user-images.githubusercontent.com/35816592/117452829-3a75c180-af12-11eb-9dc3-fc3d8b74bc99.png) Based on the [previous line](https://user-images.githubusercontent.com/35816592/117453083-84f73e00-af12-11eb-9d14-175ac7fad718.png), I'm guessing both "he"s (Murdaw) should be "I" and "me" should be "him". Or, maybe the "he" is correct, and the "me" is supposed to refer Demonlord Kameha, which this guy is not.
- [among those world](https://user-images.githubusercontent.com/35816592/117454498-3480e000-af14-11eb-9087-2197378d8c17.png) -> among those world**s**
- [Limbo key](https://user-images.githubusercontent.com/35816592/117454673-62662480-af14-11eb-8425-8de6e93fc227.png) -> Limbo Key
- [spirital](https://user-images.githubusercontent.com/35816592/117454787-83c71080-af14-11eb-97d1-fa0ceaf7b24f.png) -> spiritual
- [The plant is withering](https://user-images.githubusercontent.com/35816592/117454855-94778680-af14-11eb-97aa-c85934fdd46b.png) -> Probably "The plant**s** **are** withering." Considering that we can't see it from here, I don't think he's referring to just the one giant palm tree.
- [all the florals in Great Log](https://user-images.githubusercontent.com/35816592/117470605-fa6c0a00-af24-11eb-892e-849fa2bd2744.png): "floral" should be "flora". I can't find any use of [floral](https://en.wiktionary.org/wiki/floral#English) as a noun that refers to the actual plants.
- [Do with it as you like just don't buy the kingdom!](https://user-images.githubusercontent.com/35816592/117471269-ae6d9500-af25-11eb-9775-5e5df94d1729.png) -> Do with it as you like, just don't buy the kingdom!
- [when I look at how Great Log is now I can't just sit](https://user-images.githubusercontent.com/35816592/117519102-590aa580-af70-11eb-8666-0d1f3c49f8a9.png) -> when I look at how Great Log is now, I can't just sit

- [forceof](https://user-images.githubusercontent.com/35816592/117471520-ef65a980-af25-11eb-8501-36d5da8dfca1.png) -> force of
- [That reminds me I haven't seen](https://user-images.githubusercontent.com/35816592/117471600-086e5a80-af26-11eb-862c-4b1b6f2fabec.png) -> That reminds me, I haven't seen
- [Reading books help me](https://user-images.githubusercontent.com/35816592/117472125-91859180-af26-11eb-92bf-353fd5d1f5cd.png) -> Reading books help**s** me
- [this sentence uses two periods](https://user-images.githubusercontent.com/35816592/117472252-b417aa80-af26-11eb-8e2b-8158dec0db8d.png)
- [We the Demonlord Army under the command of Murdaw keep order](https://user-images.githubusercontent.com/35816592/117472344-c72a7a80-af26-11eb-8683-6d42422e45c2.png) -> We, the Demonlord Army under the command of Murdaw, keep order
- [All's Well](https://user-images.githubusercontent.com/35816592/117472549-02c54480-af27-11eb-9367-8f5ecefe0319.png): either _"All's well"_ (with quotes) or _all's well_ (no quotes). I can't think of any reason to capitalize both
- [Take treasures to Rottney](https://user-images.githubusercontent.com/35816592/117472869-59328300-af27-11eb-9420-c74da5e764a5.png): [Other](https://user-images.githubusercontent.com/35816592/117473044-8b43e500-af27-11eb-87e7-0c006601a3d9.png) [lines](https://user-images.githubusercontent.com/35816592/117473051-8d0da880-af27-11eb-9175-ec2fb0b2bc64.png) imply you currently don't have them, so it should be take **from** Rottney
- [current staying here](https://user-images.githubusercontent.com/35816592/117473164-a878b380-af27-11eb-9777-d2afe135e610.png) -> current**ly** staying here
- Neo Darck's "Dark Shackles" attack produces a "Damage most HP" message, but causes a "[MAX HP Down](https://user-images.githubusercontent.com/35816592/117473298-cc3bf980-af27-11eb-9666-c6980882cf5e.png)" status effect. I don't quite remember my monsters' max hp levels, so I can't tell if it's right, but the latter makes much more sense as a status effect. 
- The Prince is referred to as "Pince" in the ending.
- [increase battle speeds](https://user-images.githubusercontent.com/35816592/117473489-0a391d80-af28-11eb-8c65-f18a22699c05.png) -> increase battle speed
- [gurry to the Market](https://user-images.githubusercontent.com/35816592/117518328-55c1ea80-af6d-11eb-9372-8981c83bec8e.png) -> **h**urry to the **m**arket
  - almost every other instance of the word "market" is also capitalized for no apparent reason
- [this line from the beginning](https://user-images.githubusercontent.com/35816592/117518535-1c3daf00-af6e-11eb-894d-df63e4f27518.png) seems to give Cobi a one-time nickname based of his Japanese name
- How about TIHS for a reward

papa
- ["+25" in "some"](https://user-images.githubusercontent.com/35816592/117439480-e1516200-af00-11eb-8320-2bc874f31717.png)
- [pretty much](https://user-images.githubusercontent.com/35816592/117439575-0219b780-af01-11eb-9ee5-3b3de9ba5c63.png) [every line](https://user-images.githubusercontent.com/35816592/117439959-7bb1a580-af01-11eb-84cb-f006d36a848b.png) [during this](https://user-images.githubusercontent.com/35816592/117439989-8409e080-af01-11eb-9bc2-6f0e82977efe.png) [quest](https://user-images.githubusercontent.com/35816592/117439941-77858800-af01-11eb-9943-7158996b2ab9.png) [makes](https://user-images.githubusercontent.com/35816592/117441781-e532b380-af03-11eb-9311-bbcb0c5fc2e5.png) [no](https://user-images.githubusercontent.com/35816592/117441794-e82da400-af03-11eb-9e8d-6cb4dea937dc.png) [sense](https://user-images.githubusercontent.com/35816592/117441879-0398af00-af04-11eb-9b89-a20982010c14.png)
  - For reference, all that's needed is a monster with the Defense Boost II skill, can be unlocked by having Defense Boost maxed out on a parent (100 SP), or Defense Boost on both parents with a **sum** that is at least 100 (an not necessarily over)

---

- [feraball, chimera](https://user-images.githubusercontent.com/35816592/117438357-72bfd480-aeff-11eb-9819-04cda40ee4a5.png) -> fera**l**ball, chim**a**era

- there's no obvious pun in [dameselfly](https://user-images.githubusercontent.com/35816592/117442779-38593600-af05-11eb-909f-a2df71fd238c.png). I thought it may be an unintentional typo of the word "damsel". Going by [the previous appearances of this monster](https://dragon-quest.org/wiki/Damselfly_(DQVI)), this appears to be the case.
- [mechanowyrn](https://user-images.githubusercontent.com/35816592/117451073-06999c80-af10-11eb-88cb-6362fa8c07c8.png) is typically known as "[mechan-o'-wyrm](https://dragon-quest.org/wiki/Mechan-o%27-wyrm)". The "[wyr**m**](https://en.wiktionary.org/wiki/wyrm)" is probably the most important bit that's off.
- "hellhound" is used in the dialogue, which seems to be in line with its [previous appearances](https://dragon-quest.org/wiki/Hellhound), but in this game the monster is named "hell hound", with a space.

- There are lots of instances of [_O'_](https://en.wiktionary.org/wiki/o') (and o') that I think should instead be [_O_](https://en.wiktionary.org/wiki/O#Particle).
- there are two lines with seemingly extraneous mid sentence double spaces.
- there are still remaining instances of "exhilirating" rather than "exhilarating", "Aquaduct" rather than "Aqueduct", and "ASYIA" rather than "ASIYA".
- I noticed, upon fixing my last issue, the "s" was removed after item names for receiving multiple items at some points, but this leaves other item names as singular when they should be plural, and doesn't fix [other instances](https://user-images.githubusercontent.com/35816592/117447298-4f9b2200-af0b-11eb-9148-b2b092eb2afb.png). This only way I can think of to do this right is to somehow hardcode a pluralized version of every generic item name. It also might be possible to avoid the problem altogether with something [like this](https://user-images.githubusercontent.com/35816592/117519865-7a20c580-af73-11eb-864a-b1c08dbddcd1.png).
- one of Murdaw's line implies that he gave you the Light Orb: "I continue to exist even after I passed the Light Orb to you." Maybe I'm misremembering things, but I'm pretty sure it was Kameha that gave us the Light Orb. Either way, it might be safe to say "I continue to exist even after the Light Orb was passed to you."
- The titles for completing a world say "You traveled to X" when unlocked. If traveling there was all that was needed, the title would have unlocked upon first entering (or returning from) that world.
- there's an instance of "War" that's capitalized for no reason

**Comment by itchyd** [comment]
The post S-class arena fights have alot of untranslated text

**Comment by Ich73** [comment]
@dackst Thanks for all your efforts in submitting these issues!

-----

> The post S-class arena fights have alot of untranslated text

_Edit: I found the problem._
