### ISSUE TITLE
Hint Menu- and Summary-Texts look weird

### ISSUE THREAD

**Issue by Clydefrosch22** [Ich73/DQM2-FanTranslation#3]
Just noticed the text on the top screen for the various hints actually looks weirdly out of focus.

**Comment by Ich73** [comment]
Not only the hint texts, but also the archive and records summary of the player.

**Comment by Ich73** [comment]
If you're using a LayeredFS patch, you can now [update your workspace](https://github.com/Ich73/DQM2-FanTranslation/wiki/Installing-LayeredFS#update-workspace) using the UW script.
