### ISSUE TITLE
Need help to edit the code

### ISSUE THREAD

**Issue by Sfynx10** [Ich73/DQM2-FanTranslation#30]
Hello, i'm translating the game in french and i need your help.
I'm trying to edit the code, but i have some problems.
When i try to convert the code.bin to code.elf, i have two problems. 
First, i don't have the file "ExtractedHeaderFS.bin". I have "DecryptedExeFS","DecryptedExheader" and "HeaderExeFS". 
Second, if i try with HeaderExeFS, the converter made "ExeFS.elf" instead of "code.elf". 
I still tried to edit the elf file but i don't know what to do with IDA options when i launch the programs (which options that i have to choose.
Thank you very much.

**Comment by Ich73** [comment]
For the majority of the translation, you don't need to modify the code. The main part are the .binJ and .e files, which you can edit with [BinJ Editor](https://github.com/Ich73/BinJEditor/). I recommend starting with the easier .binJ files to get a feeling for it, e.g., msg_common, msg_countryname, msg_eggname. Once you have that, I can edit the code and help with the images as well.

**Comment by Ich73** [comment]
We can talk about this on Discord: [Dominik#9803](https://discord.com/channels/@me/644832989548642305/1044639125980073984)
