### ISSUE TITLE
Wi-Fi Battle text

### ISSUE THREAD

**Issue by Pedeadstrian** [Ich73/DQM2-FanTranslation#5]
The question is "Do you have any problems with transferring your info over the internet?" If you select no, meaning you don't have problems, the NPC will respond with "That's too bad. Please come back if you change your mind." Awfully confusing.

**Comment by Ich73** [comment]
If you're using a LayeredFS patch, you can now [update your workspace](https://github.com/Ich73/DQM2-FanTranslation/wiki/Installing-LayeredFS#update-workspace) using the UW script.
