### ISSUE TITLE
Missing translation on weapon grades

### ISSUE THREAD

**Issue by mtjohnson47** [Ich73/DQM2-FanTranslation#6]
The blacksmith has Japanese symbols (the complicated ones, not the simple ones).  I took a screenshot which I'll post later when I'm able to pull it off my 3DS.  Which will probably be Monday.

**Comment by Ich73** [comment]
I wasn't able to find what you describe, the screenshot would be helpful.

**Comment by mtjohnson47** [comment]
Sorry I forgot to upload this here
![2031-04-01_22-02-07 482_top](https://user-images.githubusercontent.com/5100948/114618492-068ae180-9c6f-11eb-9f57-74d24e0c6e34.png)
I've seen the same symbol being used to describe weapons a few other times in dialogs but don't have a screenshot

**Comment by Ich73** [comment]
Thanks! That symbol is supposed to be a ⭐.

**Comment by Ich73** [comment]
If you're using a LayeredFS patch, you can now [update your workspace](https://github.com/Ich73/DQM2-FanTranslation/wiki/Installing-LayeredFS#update-workspace) using the UW script.
