### ISSUE TITLE
"it's" vs. "its"

### ISSUE THREAD

**Issue by Ich73** [Ich73/DQM2-FanTranslation#7]
Many instances of "it's" being used instead of "its" were found.
For example something like "it's size" should be "its size".

There are 513 occurrences to check in Event_EN and 366 in Message_EN.
One can search for them using the Regex `\b[Ii][Tt]'?[Ss]\b`.

**Comment by dackst** [comment]
I've also seen some instances of *its'* where I think *its* work just fine. It's not like *somethin'* where a sound is being omitted.

**Comment by Ich73** [comment]
That's a good point. The given Regex finds them as well.
