### ISSUE TITLE
Problems patching the game.

### ISSUE THREAD

**Issue by NxJfOrEvEr** [Ich73/DQM2-FanTranslation#8]
I have the game v1.0, and update v1.1 file. Iv installed them on my 3ds "yes its has homebrew" and installed them to see if they were good rom dumps. Iv deleted them after and all the data of them too. So when I add the v1.0, v1.1 files and the patches of Eng1.0,Eng1.1 to gamepatcher the process fails. I know I have to be doing something wrong and its probably simple that I'm just not seeing it. If someone could help Id be super appreciative for the help!
![Screenshot (3)](https://user-images.githubusercontent.com/60205879/113471226-13b2ff80-9429-11eb-9d0e-b36c1a6da0bf.png)

**Comment by Ich73** [comment]
First, the image in your second post didn't finish uploading.

Please check the MD5 hashes of the cia files in order to verify that they are correct.
  * base game: `CA482BE34AF664CB2058A9EEADBE653D`
  * v1.1 update: `760B11D9BEFDAE746AE1C076A01BA75C`

You can do this on windows by running `Windows PowerShell`, navigating to the folder your cia files are in and running the command `get-filehash -algorithm MD5 *.cia`.

**Comment by NxJfOrEvEr** [comment]
Im kinda new to using powershell and commands. Once in powershell do I run
get-filehash then hit enter. An then -algorithm MD5*.cia

**Comment by Ich73** [comment]
The procedure is as follows:
  * Open `Windows Power Shell`
  * Navigate to the directory your cia files are in by using the `cd` command
    * Example: input `cd "C:\Users\MyUserName\Patching\"` and press Enter
 * Enter the full command `get-filehash -algorithm MD5 *.cia` at once and press Enter
 * Wait until the process is finished and check if the hashes printed on the console match the ones I commented

**Comment by NxJfOrEvEr** [comment]
Also if my game was updated to version 1.1 would that be what the
problem could be ? I installed the copy of the rom to my 3ds and its
already at version 1.1. I think it could be the problem but with patching
the files and everything I dont know. Im sorry if this is a no brainer to
you and not me. Im in the process of buying and shipping a cartridge for
the game from japan right now so I can dump a cop of the game fresh.

**Comment by Ich73** [comment]
That could very well be the problem, yes.
Let me know when you try it with the fresh dump if it works or not.

**Comment by NxJfOrEvEr** [comment]
Ok I most definitely will. I’m sorry again I installed the game file and
update file when at first round of all of this. Iv been following you guys
since your translation of DQM 1 was released. The game won’t be here until
April 23. But if anything I’ll be talking to you again.

**Comment by NxJfOrEvEr** [comment]
can I cancel the order I didn't realsize but I sold my 3ds during
quarantine in a lot sale. I'm sorry for the inconvenience!

**Comment by Ich73** [comment]
You can do whatever you want. No worries. 😃

**Comment by NxJfOrEvEr** [comment]
I’m sorry I didn’t mean to email you. But I did get the game working I must
of hit the space bar at some point or something. Because I’m just getting
through the intro for the game. Again you and your team have done the world
a justice that will not get enough attention! Thank you!!!
